- type: ProduceCardGrowEffectType_LessonAdd
  name: パラメータ上昇値+
  produceDescriptionId: Label_LessonAdd
- type: ProduceCardGrowEffectType_LessonReduce
  name: パラメータ上昇値-
  produceDescriptionId: Label_LessonReduce
- type: ProduceCardGrowEffectType_LessonCountAdd
  name: パラメータ上昇回数+
  produceDescriptionId: Label_LessonCountAdd
- type: ProduceCardGrowEffectType_LessonCountReduce
  name: パラメータ上昇回数-
  produceDescriptionId: Label_LessonCountReduce
- type: ProduceCardGrowEffectType_BlockAdd
  name: 元気増加値+
  produceDescriptionId: Label_BlockAdd
- type: ProduceCardGrowEffectType_BlockReduce
  name: 元気増加値-
  produceDescriptionId: Label_BlockReduce
- type: ProduceCardGrowEffectType_FullPowerPointAdd
  name: 全力値増加値+
  produceDescriptionId: Label_FullPowerPointAdd
- type: ProduceCardGrowEffectType_FullPowerPointReduce
  name: 全力値増加値-
  produceDescriptionId: Label_FullPowerPointReduce
- type: ProduceCardGrowEffectType_CostBuffReduce
  name: 強化状態コスト減少
  produceDescriptionId: Label_CostBuffReduce
- type: ProduceCardGrowEffectType_CostBuffAdd
  name: 強化状態コスト増加
  produceDescriptionId: Label_CostBuffAdd
- type: ProduceCardGrowEffectType_CostReduce
  name: コスト減少
  produceDescriptionId: Label_CostReduce
- type: ProduceCardGrowEffectType_CostAdd
  name: コスト増加
  produceDescriptionId: Label_CostAdd
- type: ProduceCardGrowEffectType_CostPenetrateReduce
  name: 体力消費コスト減少
  produceDescriptionId: Label_CostPenetrateReduce
- type: ProduceCardGrowEffectType_CostPenetrateAdd
  name: 体力消費コスト増加
  produceDescriptionId: Label_CostPenetrateAdd
- type: 16
  name: 好調増加値+
  produceDescriptionId: Label_ParameterBuffTurnAdd
- type: 17
  name: 好調増加値-
  produceDescriptionId: Label_ParameterBuffTurnReduce
- type: 18
  name: 集中増加値+
  produceDescriptionId: Label_LessonBuffAdd
- type: 19
  name: 集中増加値-
  produceDescriptionId: Label_LessonBuffReduce
- type: 20
  name: 好印象増加値+
  produceDescriptionId: Label_ReviewAdd
- type: 21
  name: 好印象増加値-
  produceDescriptionId: Label_ReviewReduce
- type: 22
  name: やる気増加値+
  produceDescriptionId: Label_AggressiveAdd
- type: 23
  name: やる気増加値-
  produceDescriptionId: Label_AggressiveReduce
- type: 24
  name: ドロー枚数+
  produceDescriptionId: Label_CardDrawAdd
- type: 25
  name: ドロー枚数-
  produceDescriptionId: Label_CardDrawReduce
- type: 26
  name: 絶好調増加値+
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnAdd
- type: 27
  name: 絶好調増加値-
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnReduce
- type: 28
  name: 消費体力-増加値+
  produceDescriptionId: Label_StaminaConsumptionDownTurnAdd
- type: 29
  name: 消費体力-増加値-
  produceDescriptionId: Label_StaminaConsumptionDownTurnReduce
- type: 30
  name: 消費体力+増加値-
  produceDescriptionId: Label_StaminaConsumptionAddTurnAdd
- type: 31
  name: 消費体力+増加値+
  produceDescriptionId: Label_StaminaConsumptionAddTurnReduce
- type: 32
  name: 効果追加
  produceDescriptionId: Label_EffectAdd
- type: 33
  name: 効果削除
  produceDescriptionId: Label_EffectDelete
- type: 34
  name: 効果置換
  produceDescriptionId: Label_EffectChange
- type: 35
  name: 成長効果置換
  produceDescriptionId: Label_CardStatusEnchantChange
- type: 36
  name: 使用可能条件を置換
  produceDescriptionId: Label_PlayTriggerChange
- type: 37
  name: 効果発動条件を置換
  produceDescriptionId: Label_PlayEffectTriggerChange
- type: 38
  name: 使用後移動先変更
  produceDescriptionId: Label_PlayMovePositionTypeChange
- type: 39
  name: 開始時手札効果付与
  produceDescriptionId: Label_InitialAdd