- examProduceDescriptionId: Label_ExamLesson
  name: パラメータ
  noIcon: true
  noReference: true
  produceDescriptionId: Label_ExamLesson
  swapName: スコア
  type: ProduceExamEffectType_ExamLesson
- examProduceDescriptionId: Label_ExamParameterBuff
  mainBuffMinThresholds:
    - 3
    - 5
  name: 好調
  produceDescriptionId: Label_ExamParameterBuff
  swapName: 好調
  type: ProduceExamEffectType_ExamParameterBuff
- examProduceDescriptionId: Label_ExamBlock
  name: 元気
  produceDescriptionId: Label_ExamBlock
  swapName: 元気
  type: ProduceExamEffectType_ExamBlock
- examProduceDescriptionId: Label_ExamCardDraw
  name: スキルカードを引く
  noReference: true
  produceDescriptionId: Label_ExamCardDraw
  swapName: スキルカードを引く
  type: ProduceExamEffectType_ExamCardDraw
- examProduceDescriptionId: Label_ExamStaminaConsumptionDown
  name: 消費体力減少
  produceDescriptionId: Label_ExamStaminaConsumptionDown
  swapName: 消費体力減少
  type: ProduceExamEffectType_ExamStaminaConsumptionDown
- examProduceDescriptionId: Label_ExamCardCreateId
  name: 生成
  produceDescriptionId: Label_ExamCardCreateId
  swapName: 生成
  type: ProduceExamEffectType_ExamCardCreateId
- examProduceDescriptionId: Label_ExamStaminaReduceFix
  name: 体力消費
  produceDescriptionId: Label_ExamStaminaReduceFix
  swapName: 体力消費
  type: ProduceExamEffectType_ExamStaminaReduceFix
- examProduceDescriptionId: Label_ExamLessonBuff_Exam
  mainBuffMinThresholds:
    - 5
    - 10
  name: 集中
  produceDescriptionId: Label_ExamLessonBuff_Produce
  swapName: 集中
  type: ProduceExamEffectType_ExamLessonBuff
- examProduceDescriptionId: Label_ExamCardUpgrade
  name: レッスン中強化
  produceDescriptionId: Label_ExamCardUpgrade
  swapName: 試験中強化
  type: ProduceExamEffectType_ExamCardUpgrade
- examProduceDescriptionId: Label_ExamPlayableValueAdd_Exam
  name: スキルカード使用数追加
  produceDescriptionId: Label_ExamPlayableValueAdd_Produce
  swapName: スキルカード使用数追加
  type: ProduceExamEffectType_ExamPlayableValueAdd
- examProduceDescriptionId: Label_ExamLessonBuffMultiple
  name: 集中効果一時増加
  produceDescriptionId: Label_ExamLessonBuffMultiple
  swapName: 集中効果一時増加
  type: ProduceExamEffectType_ExamLessonBuffMultiple
- examProduceDescriptionId: Label_ExamCardStaminaConsumptionChange
  name: 消費体力変化
  produceDescriptionId: Label_ExamCardStaminaConsumptionChange
  swapName: 消費体力変化
  type: ProduceExamEffectType_ExamCardStaminaConsumptionChange
- examProduceDescriptionId: Label_ExamBlockRestriction
  name: 元気増加無効
  produceDescriptionId: Label_ExamBlockRestriction
  swapName: 元気増加無効
  type: ProduceExamEffectType_ExamBlockRestriction
- examProduceDescriptionId: Label_ExamStatusEnchant
  name: 持続効果
  produceDescriptionId: Label_ExamStatusEnchant
  swapName: 持続効果
  type: ProduceExamEffectType_ExamStatusEnchant
- examProduceDescriptionId: Label_ExamCardStaminaConsumptionDownSpecify
  name: 消費体力低下
  produceDescriptionId: Label_ExamCardStaminaConsumptionDownSpecify
  swapName: 消費体力低下
  type: ProduceExamEffectType_ExamCardStaminaConsumptionDownSpecify
- examProduceDescriptionId: Label_ExamLessonFix
  name: 固定パラメータ
  produceDescriptionId: Label_ExamLessonFix
  swapName: 固定スコア
  type: ProduceExamEffectType_ExamLessonFix
- examProduceDescriptionId: Label_ExamCardDuplicate
  name: 複製
  produceDescriptionId: Label_ExamCardDuplicate
  swapName: 複製
  type: ProduceExamEffectType_ExamCardDuplicate
- examProduceDescriptionId: Label_ExamReview_Exam
  mainBuffMinThresholds:
    - 5
    - 10
  name: 好印象
  produceDescriptionId: Label_ExamReview_Produce
  swapName: 好印象
  type: ProduceExamEffectType_ExamReview
- examProduceDescriptionId: Label_ExamCardSearchEffectPlayCountBuff
  name: スキルカード追加発動
  produceDescriptionId: Label_ExamCardSearchEffectPlayCountBuff
  swapName: スキルカード追加発動
  type: ProduceExamEffectType_ExamCardSearchEffectPlayCountBuff
- examProduceDescriptionId: Label_ExamLessonValueMultiple
  name: パラメータ上昇量増加
  produceDescriptionId: Label_ExamLessonValueMultiple
  swapName: スコア上昇量増加
  type: ProduceExamEffectType_ExamLessonValueMultiple
- examProduceDescriptionId: Label_ExamCardPlayAggressive_Exam
  mainBuffMinThresholds:
    - 5
    - 10
  name: やる気
  produceDescriptionId: Label_ExamCardPlayAggressive_Produce
  swapName: やる気
  type: ProduceExamEffectType_ExamCardPlayAggressive
- examProduceDescriptionId: Label_ExamConcentration
  name: 強気
  produceDescriptionId: Label_ExamConcentration
  swapName: 強気
  type: ProduceExamEffectType_ExamConcentration
- examProduceDescriptionId: Label_ExamPreservation
  name: 温存
  produceDescriptionId: Label_ExamPreservation
  swapName: 温存
  type: ProduceExamEffectType_ExamPreservation
- examProduceDescriptionId: Label_ExamFullPower_Exam
  name: 全力
  produceDescriptionId: Label_ExamFullPower_Produce
  swapName: 全力
  type: ProduceExamEffectType_ExamFullPower
- examProduceDescriptionId: Label_ExamFullPowerPoint
  mainBuffMinThresholds:
    - 5
    - 10
  name: 全力値
  produceDescriptionId: Label_ExamFullPowerPoint
  swapName: 全力値
  type: ProduceExamEffectType_ExamFullPowerPoint
- examProduceDescriptionId: Label_ExamSearchPlayCardStaminaConsumptionChange
  name: 消費体力変化
  produceDescriptionId: Label_ExamSearchPlayCardStaminaConsumptionChange
  swapName: 消費体力変化
  type: ProduceExamEffectType_ExamSearchPlayCardStaminaConsumptionChange
- examProduceDescriptionId: Label_ExamUplifting_Exam
  name: 高揚
  produceDescriptionId: Label_ExamUplifting_Produce
  swapName: 高揚
  type: ProduceExamEffectType_ExamUplifting
- examProduceDescriptionId: Label_ExamExtraTurn
  name: ターン追加
  produceDescriptionId: Label_ExamExtraTurn
  swapName: ターン追加
  type: ProduceExamEffectType_ExamExtraTurn
- examProduceDescriptionId: Label_ExamAntiDebuff
  name: 低下状態無効
  produceDescriptionId: Label_ExamAntiDebuff
  swapName: 低下状態無効
  type: ProduceExamEffectType_ExamAntiDebuff
- examProduceDescriptionId: Label_ExamStaminaConsumptionAdd
  name: 消費体力増加
  produceDescriptionId: Label_ExamStaminaConsumptionAdd
  swapName: 消費体力増加
  type: ProduceExamEffectType_ExamStaminaConsumptionAdd
- examProduceDescriptionId: Label_ExamBlockAddDown
  name: 不安
  produceDescriptionId: Label_ExamBlockAddDown
  swapName: 不安
  type: ProduceExamEffectType_ExamBlockAddDown
- examProduceDescriptionId: Label_ExamBlockAddDownRestriction
  name: 不安無効
  produceDescriptionId: Label_ExamBlockAddDownRestriction
  swapName: 不安無効
  type: ProduceExamEffectType_ExamBlockAddDownRestriction
- examProduceDescriptionId: Label_ExamStaminaRecoverAdd
  name: 体力回復効果増加
  produceDescriptionId: Label_ExamStaminaRecoverAdd
  swapName: 体力回復効果増加
  type: ProduceExamEffectType_ExamStaminaRecoverAdd
- examProduceDescriptionId: Label_ExamStaminaReduceChange
  name: 体力消費軽減
  produceDescriptionId: Label_ExamStaminaReduceChange
  swapName: 体力消費軽減
  type: ProduceExamEffectType_ExamStaminaReduceChange
- examProduceDescriptionId: Label_ExamPanic
  name: 気まぐれ
  produceDescriptionId: Label_ExamPanic
  swapName: 気まぐれ
  type: ProduceExamEffectType_ExamPanic
- examProduceDescriptionId: Label_ExamLessonChangeSpecifyLessThan
  name: パラメータ上昇値変更
  produceDescriptionId: Label_ExamLessonChangeSpecifyLessThan
  swapName: スコア上昇値変更
  type: ProduceExamEffectType_ExamLessonChangeSpecifyLessThan
- examProduceDescriptionId: Label_ExamHandHold
  name: 手札持ち越し
  produceDescriptionId: Label_ExamHandHold
  swapName: 手札持ち越し
  type: ProduceExamEffectType_ExamHandHold
- examProduceDescriptionId: Label_ExamStaminaConsumptionAddFix
  name: 消費体力追加
  produceDescriptionId: Label_ExamStaminaConsumptionAddFix
  swapName: 消費体力追加
  type: ProduceExamEffectType_ExamStaminaConsumptionAddFix
- examProduceDescriptionId: Label_ExamStaminaConsumptionAddDown
  name: 消費体力増加効果減少
  produceDescriptionId: Label_ExamStaminaConsumptionAddDown
  swapName: 消費体力増加効果減少
  type: ProduceExamEffectType_ExamStaminaConsumptionAddDown
- examProduceDescriptionId: Label_ExamStaminaRecoverRestriction
  name: 体力回復不可
  produceDescriptionId: Label_ExamStaminaRecoverRestriction
  swapName: 体力回復不可
  type: ProduceExamEffectType_ExamStaminaRecoverRestriction
- examProduceDescriptionId: Label_ExamStaminaConsumptionDownAdd
  name: 消費体力減少効果増加
  produceDescriptionId: Label_ExamStaminaConsumptionDownAdd
  swapName: 消費体力減少効果増加
  type: ProduceExamEffectType_ExamStaminaConsumptionDownAdd
- examProduceDescriptionId: Label_ExamGetCardUpgrade
  name: 生成強化
  produceDescriptionId: Label_ExamGetCardUpgrade
  swapName: 生成強化
  type: ProduceExamEffectType_ExamGetCardUpgrade
- examProduceDescriptionId: Label_ExamStaminaConsumptionDownFix
  name: 消費体力削減
  produceDescriptionId: Label_ExamStaminaConsumptionDownFix
  swapName: 消費体力削減
  type: ProduceExamEffectType_ExamStaminaConsumptionDownFix
- examProduceDescriptionId: Label_ExamHandGraveCountCardDraw
  name: 手札を入れ替える
  noReference: true
  produceDescriptionId: Label_ExamHandGraveCountCardDraw
  swapName: 手札を入れ替える
  type: ProduceExamEffectType_ExamHandGraveCountCardDraw
- examProduceDescriptionId: Label_ExamEffectTimer
  name: 発動予約
  produceDescriptionId: Label_ExamEffectTimer
  swapName: 発動予約
  type: ProduceExamEffectType_ExamEffectTimer
- examProduceDescriptionId: Label_ExamGimmickLessonDebuff_Exam
  name: 集中減少
  produceDescriptionId: Label_ExamGimmickLessonDebuff_Produce
  swapName: 集中減少
  type: ProduceExamEffectType_ExamGimmickLessonDebuff
- examProduceDescriptionId: Label_ExamGimmickParameterDebuff
  name: 不調
  produceDescriptionId: Label_ExamGimmickParameterDebuff
  swapName: 不調
  type: ProduceExamEffectType_ExamGimmickParameterDebuff
- examProduceDescriptionId: Label_ExamGimmickSleepy_Exam
  name: 弱気
  produceDescriptionId: Label_ExamGimmickSleepy_Produce
  swapName: 弱気
  type: ProduceExamEffectType_ExamGimmickSleepy
- examProduceDescriptionId: Label_ExamGimmickEnthusiastic_Exam
  name: 熱意
  produceDescriptionId: Label_ExamGimmickEnthusiastic_Produce
  swapName: 熱意
  type: ProduceExamEffectType_ExamGimmickEnthusiastic
- examProduceDescriptionId: Label_ExamGimmickPlayCardLimit
  name: 使用不可
  produceDescriptionId: Label_ExamGimmickPlayCardLimit
  swapName: 使用不可
  type: ProduceExamEffectType_ExamGimmickPlayCardLimit
- examProduceDescriptionId: Label_ExamGimmickSlump
  name: スランプ
  produceDescriptionId: Label_ExamGimmickSlump
  swapName: スランプ
  type: ProduceExamEffectType_ExamGimmickSlump
- examProduceDescriptionId: Label_ExamGimmickStartTurnCardDrawDown_Exam
  name: 手札減少
  produceDescriptionId: Label_ExamGimmickStartTurnCardDrawDown_Produce
  swapName: 手札減少
  type: ProduceExamEffectType_ExamGimmickStartTurnCardDrawDown
- examProduceDescriptionId: Label_ExamBlockFix
  name: 固定元気
  produceDescriptionId: Label_ExamBlockFix
  swapName: 固定元気
  type: ProduceExamEffectType_ExamBlockFix
- examProduceDescriptionId: Label_ExamLessonChangeSpecifyMoreThan
  name: うわの空
  produceDescriptionId: Label_ExamLessonChangeSpecifyMoreThan
  swapName: うわの空
  type: ProduceExamEffectType_ExamLessonChangeSpecifyMoreThan
- examProduceDescriptionId: Label_ExamParameterBuffMultiplePerTurn
  name: 絶好調
  produceDescriptionId: Label_ExamParameterBuffMultiplePerTurn
  swapName: 絶好調
  type: ProduceExamEffectType_ExamParameterBuffMultiplePerTurn