- type: ProduceEffectType_VocalAddition
  name: ボーカル上昇
  produceDescriptionLabelId: ""
- type: ProduceEffectType_DanceAddition
  name: ダンス上昇
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VisualAddition
  name: ビジュアル上昇
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VocalDown
  name: ボーカル低下
  produceDescriptionLabelId: ""
- type: ProduceEffectType_DanceDown
  name: ダンス低下
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VisualDown
  name: ビジュアル低下
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VocalGrowthRateAddition
  name: ボーカルレッスンボーナス+
  produceDescriptionLabelId: ""
- type: ProduceEffectType_DanceGrowthRateAddition
  name: ダンスレッスンボーナス+
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VisualGrowthRateAddition
  name: ビジュアルレッスンボーナス+
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VocalGrowthRateDown
  name: ボーカルレッスンボーナス-
  produceDescriptionLabelId: ""
- type: ProduceEffectType_DanceGrowthRateDown
  name: ダンスレッスンボーナス-
  produceDescriptionLabelId: ""
- type: ProduceEffectType_VisualGrowthRateDown
  name: ビジュアルレッスンボーナス-
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaRecoverFix
  name: 体力回復
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaRecoverMultiple
  name: 体力割合回復
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaReduceFix
  name: 体力減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaReduceMultiple
  name: 体力割合減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaSpecify
  name: 体力変更
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaRecoverValueUp
  name: 体力回復量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaRecoverValueDown
  name: 体力回復量減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaReduceValueUp
  name: 体力減少量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaReduceValueDown
  name: 体力減少量軽減
  produceDescriptionLabelId: ""
- type: ProduceEffectType_StaminaRecoverDisable
  name: 体力回復無効
  produceDescriptionLabelId: ""
- type: ProduceEffectType_MaxStaminaAddition
  name: 最大体力増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_MaxStaminaReduceFix
  name: 最大体力減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_MaxStaminaReduceMultiple
  name: 最大体力割合減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointReduceFix
  name: Pポイント減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointReduceMultiple
  name: Pポイント割合減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointSpecify
  name: Pポイント変更
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointAdditionValueUp
  name: Pポイント獲得量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointAdditionValueDown
  name: Pポイント獲得量減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointReduceValueUp
  name: Pポイント減少量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointReduceValueDown
  name: Pポイント減少量減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceCardUpgrade
  name: 強化
  produceDescriptionLabelId: Label_ProduceCardUpgrade
- type: ProduceEffectType_ProduceCardDuplicate
  name: コピー
  produceDescriptionLabelId: Label_ProduceCardDuplicate
- type: ProduceEffectType_ProduceCardDuplicateUpgrade
  name: コピーして強化
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceCardChange
  name: チェンジ
  produceDescriptionLabelId: Label_ProduceCardChange
- type: ProduceEffectType_ProduceCardChangeUpgrade
  name: チェンジして強化
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceCardDelete
  name: 削除
  produceDescriptionLabelId: Label_ProduceCardDelete
- type: ProduceEffectType_ProducePointAddition
  name: Pポイント獲得
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointGetDisable
  name: Pポイント獲得不可
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceItemGetDisable
  name: Pアイテム獲得不可
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceDrinkGetDisable
  name: Pドリンク獲得不可
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceReward
  name: 報酬獲得
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceRewardSet
  name: 報酬獲得
  produceDescriptionLabelId: ""
- type: ProduceEffectType_AuditionParameterBonusMultiple
  name: スコアボーナス増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonSpChangeRatePermilAddition
  name: SPレッスン発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonVocalSpChangeRatePermilAddition
  name: ボーカルSPレッスン発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonDanceSpChangeRatePermilAddition
  name: ダンスSPレッスン発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonVisualSpChangeRatePermilAddition
  name: ビジュアルSPレッスン発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonSpChangeRatePermilDown
  name: SPレッスン発生率減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ExamStatusEnchant
  name: レッスン時発生効果
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonPresentProduceCardRewardCountUp
  name: レッスン報酬のスキルカード選択肢追加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonPresentProduceCardRewardCountDown
  name: レッスン報酬のスキルカード選択肢減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopPriceDiscountMultiple
  name: 相談の全項目を割引
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardPriceDiscountMultiple
  name: 相談のスキルカードを割引
  produceDescriptionLabelId: Label_ShopProduceCardPriceDiscountMultiple
- type: ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple
  name: 相談のPドリンクを割引
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple
  name: 相談のスキルカード強化を割引
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardUpgradePriceSpecify
  name: 相談のスキルカード強化を変更
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple
  name: 相談のスキルカード削除を割引
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardDeletePriceSpecify
  name: 相談のスキルカード強化を変更
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceResultRewardMoneyUp
  name: プロデュース完了時の獲得マニー増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp
  name: プロデュース完了時のサポートPt増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_SupportCardEventStaminaRecoverUp
  name: サポートイベントの体力回復量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_SupportCardEventProducePointAdditionValueUp
  name: サポートイベントのPポイント獲得量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_SupportCardEventParameterAdditionValueUp
  name: サポートイベントのパラメータ上昇量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_SupportCardEventProbabilityUp
  name: サポートイベント発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_LessonPresentProducePointUp
  name: レッスン報酬のPポイント獲得量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp
  name: レッスンサポート発生率増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProduceCardSelectRerollCountUp
  name: 再抽選回数増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ProducePointAdditionDisableTrigger
  name: 初期Pポイント増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ExamTurnUp
  name: ターン数増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ExamTurnDown
  name: ターン数減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_AuditionNpcEnhance
  name: ライバルのスコア増加
  produceDescriptionLabelId: Label_AuditionNpcEnhance
- type: ProduceEffectType_ShopPriceUpMultiple
  name: 相談の全項目を割増
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardPriceUpMultiple
  name: 相談のスキルカードを割増
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceDrinkPriceUpMultiple
  name: 相談のPドリンクを割増
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardUpgradePriceUpMultiple
  name: 相談のスキルカード強化を割増
  produceDescriptionLabelId: ""
- type: ProduceEffectType_ShopProduceCardDeletePriceUpMultiple
  name: 相談のスキルカード削除を割増
  produceDescriptionLabelId: ""
- type: ProduceEffectType_EventSchoolStaminaUp
  name: 授業の消費体力増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_EventSchoolStaminaDown
  name: 授業の消費体力減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_EventActivityProducePointUp
  name: お出かけの消費Pポイント増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_EventActivityProducePointDown
  name: お出かけの消費Pポイント減少
  produceDescriptionLabelId: ""
- type: ProduceEffectType_BeforeAuditionRefreshStaminaUp
  name: 試験前体力回復量増加
  produceDescriptionLabelId: ""
- type: ProduceEffectType_BeforeAuditionRefreshStaminaDown
  name: 試験前体力回復量減少
  produceDescriptionLabelId: ""