- type: ProduceCardMovePositionType_Hand
  produceDescriptionLabelId: Label_ProduceCardPositionType_Hand
  produceCardProduceDescriptionLabelId: ""
- type: ProduceCardMovePositionType_DeckFirst
  produceDescriptionLabelId: Label_ProduceCardPositionType_DeckFirst
  produceCardProduceDescriptionLabelId: ""
- type: ProduceCardMovePositionType_DeckLast
  produceDescriptionLabelId: Label_ProduceCardPositionType_DeckLast
  produceCardProduceDescriptionLabelId: ""
- type: ProduceCardMovePositionType_DeckRandom
  produceDescriptionLabelId: Label_ProduceCardPositionType_DeckRandom
  produceCardProduceDescriptionLabelId: ""
- type: ProduceCardMovePositionType_Grave
  produceDescriptionLabelId: Label_ProduceCardPositionType_Grave
  produceCardProduceDescriptionLabelId: ""
- type: ProduceCardMovePositionType_Lost
  produceDescriptionLabelId: Label_ProduceCardPositionType_Lost
  produceCardProduceDescriptionLabelId: Label_ProduceCardMovePositionType_Lost
- type: ProduceCardMovePositionType_Hold
  produceDescriptionLabelId: Label_ProduceCardPositionType_Hold
  produceCardProduceDescriptionLabelId: ""