- assetId: img_general_pdrink_1-001
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamLesson
      targetId: Label_ExamLesson
      text: パラメータ
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+10</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_lesson-000
  id: pdrink_00-1-001
  name: 初星水
  order: "100010000001"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_lesson-0010-01
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_1-004
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamBlock
      targetId: Label_ExamBlock
      text: 元気
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+7</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_block-000
  id: pdrink_00-1-004
  name: 烏龍茶
  order: "100010000004"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_block-0007
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_2-001
  descriptions:
    - text: 手札をすべて入れ替える
      type: ProduceDescriptionType_PlainText
    - text: |2-
        体力回復<nobr>2</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_hand_grave_count_card_draw-000
    - effect_group-visible-stamina_recover_fix-000
  id: pdrink_00-2-001
  name: ミックススムージー
  order: "200010000001"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_hand_grave_count_card_draw
    - p_drink_effect-e_effect-exam_stamina_recover_fix-0002
  rarity: ProduceDrinkRarity_Sr
  unlockProducerLevel: 8
- assetId: img_general_pdrink_2-003
  descriptions:
    - text: 体力回復<nobr>6</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-stamina_recover_fix-000
  id: pdrink_00-2-003
  name: リカバリドリンク
  order: "200010000003"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_stamina_recover_fix-0006
  rarity: ProduceDrinkRarity_Sr
  unlockProducerLevel: 15
- assetId: img_general_pdrink_2-004
  descriptions:
    - text: 手札をすべて
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamCardUpgrade
      targetId: Label_ExamCardUpgrade
      text: レッスン中強化
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: |2-
        体力回復<nobr>3</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_card_upgrade-000
    - effect_group-visible-stamina_recover_fix-000
  id: pdrink_00-2-004
  name: フレッシュビネガー
  order: "200010000004"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_card_upgrade-p_card_search-hand-all-0_0
    - p_drink_effect-e_effect-exam_stamina_recover_fix-0003
  rarity: ProduceDrinkRarity_Sr
- assetId: img_general_pdrink_3-001
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamPlayableValueAdd
      targetId: Label_ExamPlayableValueAdd_Produce
      text: スキルカード使用数追加
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+1</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_playable_value_add-000
  id: pdrink_00-3-001
  name: 初星ホエイプロテイン
  order: "300010000001"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_playable_value_add-01
  rarity: ProduceDrinkRarity_Ssr
- assetId: img_general_pdrink_3-005
  descriptions:
    - text: ランダムな強化済みスキルカード（SSR）を、手札に
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamCardCreateId
      targetId: Label_ExamCardCreateId
      text: 生成
      type: ProduceDescriptionType_ProduceExamEffectType
  id: pdrink_00-3-005
  name: 初星スペシャル青汁
  order: "300010000005"
  planType: ProducePlanType_Common
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_card_create_search-0001-p_card_search-random-random_pool-p_random_pool-ssr-upgrade_1-1-hand-random-1_1
  rarity: ProduceDrinkRarity_Ssr
  unlockProducerLevel: 15
- assetId: img_general_pdrink_1-002
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamParameterBuff
      targetId: Label_ExamParameterBuff
      text: 好調
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>3ターン</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_parameter_buff-000
  id: pdrink_01-1-002
  name: ビタミンドリンク
  order: "110010000002"
  planType: ProducePlanType_Plan1
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_parameter_buff-03
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_1-003
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamLessonBuff
      targetId: Label_ExamLessonBuff_Produce
      text: 集中
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+3</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_lesson_buff-000
  id: pdrink_01-1-003
  name: アイスコーヒー
  order: "110010000003"
  planType: ProducePlanType_Plan1
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_lesson_buff-0003
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_2-005
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamParameterBuffMultiplePerTurn
      targetId: Label_ExamParameterBuffMultiplePerTurn
      text: 絶好調
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>1ターン</nobr>
      type: ProduceDescriptionType_PlainText
    - text: |2+
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamBlock
      targetId: Label_ExamBlock
      text: 元気
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+9</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_block-000
    - effect_group-visible-exam_parameter_buff_multiple_per_turn-000
  id: pdrink_01-2-005
  name: スタミナ爆発ドリンク
  order: "210010000005"
  planType: ProducePlanType_Plan1
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_parameter_buff_multiple_per_turn-01
    - p_drink_effect-e_effect-exam_block-0009
  rarity: ProduceDrinkRarity_Sr
  unlockProducerLevel: 21
- assetId: img_general_pdrink_3-002
  descriptions:
    - text: 以降、ターン終了時、
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamLessonBuff
      targetId: Label_ExamLessonBuff_Produce
      text: 集中
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+1</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_status_enchant-000
    - effect_group-visible-exam_lesson_buff-000
  id: pdrink_01-3-002
  name: 厳選初星マキアート
  order: "310010000002"
  planType: ProducePlanType_Plan1
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_01-3-002-enc01
  rarity: ProduceDrinkRarity_Ssr
  unlockProducerLevel: 27
- assetId: img_general_pdrink_3-004
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamParameterBuffMultiplePerTurn
      targetId: Label_ExamParameterBuffMultiplePerTurn
      text: 絶好調
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>2ターン</nobr>
      type: ProduceDescriptionType_PlainText
    - text: |2-
        手札をすべて
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamCardUpgrade
      targetId: Label_ExamCardUpgrade
      text: レッスン中強化
      type: ProduceDescriptionType_ProduceExamEffectType
  effectGroupIds:
    - effect_group-visible-exam_card_upgrade-000
    - effect_group-visible-exam_parameter_buff_multiple_per_turn-000
  id: pdrink_01-3-004
  name: 初星ブーストエナジー
  order: "310010000004"
  planType: ProducePlanType_Plan1
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_parameter_buff_multiple_per_turn-02
    - p_drink_effect-e_effect-exam_card_upgrade-p_card_search-hand-all-0_0
  rarity: ProduceDrinkRarity_Ssr
  unlockProducerLevel: 26
- assetId: img_general_pdrink_1-006
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamReview
      targetId: Label_ExamReview_Produce
      text: 好印象
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+3</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_review-000
  id: pdrink_02-1-006
  name: ルイボスティー
  order: "120010000006"
  planType: ProducePlanType_Plan2
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_review-0003
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_1-008
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
      targetId: Label_ExamCardPlayAggressive_Produce
      text: やる気
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+3</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_card_play_aggressive-000
  id: pdrink_02-1-008
  name: ホットコーヒー
  order: "120010000008"
  planType: ProducePlanType_Plan2
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_card_play_aggressive-0003
  rarity: ProduceDrinkRarity_R
- assetId: img_general_pdrink_2-006
  descriptions:
    - examEffectType: ProduceExamEffectType_ExamReview
      targetId: Label_ExamReview_Produce
      text: 好印象
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: の<nobr>100%</nobr>分
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamLesson
      targetId: Label_ExamLesson
      text: パラメータ
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: 上昇
      type: ProduceDescriptionType_PlainText
    - text: |2+
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamBlock
      targetId: Label_ExamBlock
      text: 元気
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+3</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_lesson-000
    - effect_group-visible-exam_block-000
  id: pdrink_02-2-006
  name: おしゃれハーブティー
  order: "220010000006"
  planType: ProducePlanType_Plan2
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_lesson_depend_exam_review-1000-01
    - p_drink_effect-e_effect-exam_block-0003
  rarity: ProduceDrinkRarity_Sr
  unlockProducerLevel: 21
- assetId: img_general_pdrink_3-006
  descriptions:
    - text: 以降、ターン終了時、
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamReview
      targetId: Label_ExamReview_Produce
      text: 好印象
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+1</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_status_enchant-000
    - effect_group-visible-exam_review-000
  id: pdrink_02-3-006
  name: 厳選初星ティー
  order: "320010000006"
  planType: ProducePlanType_Plan2
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-006-enc01
  rarity: ProduceDrinkRarity_Ssr
  unlockProducerLevel: 27
- assetId: img_general_pdrink_3-007
  descriptions:
    - text: 以降、ターン終了時、
      type: ProduceDescriptionType_PlainText
    - examEffectType: ProduceExamEffectType_ExamCardPlayAggressive
      targetId: Label_ExamCardPlayAggressive_Produce
      text: やる気
      type: ProduceDescriptionType_ProduceExamEffectType
    - text: <nobr>+1</nobr>
      type: ProduceDescriptionType_PlainText
  effectGroupIds:
    - effect_group-visible-exam_status_enchant-000
    - effect_group-visible-exam_card_play_aggressive-000
  id: pdrink_02-3-007
  name: 厳選初星ブレンド
  order: "320010000007"
  planType: ProducePlanType_Plan2
  produceDrinkEffectIds:
    - p_drink_effect-e_effect-exam_status_enchant-inf-enchant-pdrink_02-3-007-enc01
  rarity: ProduceDrinkRarity_Ssr
  unlockProducerLevel: 26