- backgroundAssetId: img_general_icon_produce-effect_bg-vocal
  iconAssetId: img_general_icon_produce-effect_pict-vocal
  type: ProduceEffectType_VocalAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-dance
  iconAssetId: img_general_icon_produce-effect_pict-dance
  type: ProduceEffectType_DanceAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-visual
  iconAssetId: img_general_icon_produce-effect_pict-visual
  type: ProduceEffectType_VisualAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-vocal
  type: ProduceEffectType_VocalDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-dance
  type: ProduceEffectType_DanceDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-visual
  type: ProduceEffectType_VisualDown
- backgroundAssetId: img_general_icon_produce-effect_bg-vocal
  iconAssetId: img_general_icon_produce-effect_pict-vocalgrowthrate
  type: ProduceEffectType_VocalGrowthRateAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-dance
  iconAssetId: img_general_icon_produce-effect_pict-dancegrowthrate
  type: ProduceEffectType_DanceGrowthRateAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-visual
  iconAssetId: img_general_icon_produce-effect_pict-visualgrowthrate
  type: ProduceEffectType_VisualGrowthRateAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-vocalgrowthrate
  type: ProduceEffectType_VocalGrowthRateDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-dancegrowthrate
  type: ProduceEffectType_DanceGrowthRateDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-visualgrowthrate
  type: ProduceEffectType_VisualGrowthRateDown
- backgroundAssetId: img_general_icon_produce-effect_bg-stamina
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  type: ProduceEffectType_StaminaRecoverFix
- backgroundAssetId: img_general_icon_produce-effect_bg-stamina
  iconAssetId: img_general_icon_produce-effect_pict-staminamultiple
  type: ProduceEffectType_StaminaRecoverMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  type: ProduceEffectType_StaminaReduceFix
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-staminamultiple
  type: ProduceEffectType_StaminaReduceMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-normal
  iconAssetId: img_general_icon_produce-effect_pict-stamina
  type: ProduceEffectType_StaminaSpecify
- backgroundAssetId: img_general_icon_produce-effect_bg-stamina
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  type: ProduceEffectType_StaminaRecoverValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  type: ProduceEffectType_StaminaRecoverValueDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-staminareducevalue
  type: ProduceEffectType_StaminaReduceValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-stamina
  iconAssetId: img_general_icon_produce-effect_pict-staminareducevalue
  type: ProduceEffectType_StaminaReduceValueDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-staminarecovervalue
  type: ProduceEffectType_StaminaRecoverDisable
- backgroundAssetId: img_general_icon_produce-effect_bg-stamina
  iconAssetId: img_general_icon_produce-effect_pict-maxstamina
  type: ProduceEffectType_MaxStaminaAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-maxstamina
  type: ProduceEffectType_MaxStaminaReduceFix
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-maxstaminamultiple
  type: ProduceEffectType_MaxStaminaReduceMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  type: ProduceEffectType_ProducePointReduceFix
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-producepointmultiple
  type: ProduceEffectType_ProducePointReduceMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-normal
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  type: ProduceEffectType_ProducePointSpecify
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  type: ProduceEffectType_ProducePointAdditionValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  type: ProduceEffectType_ProducePointAdditionValueDown
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  type: ProduceEffectType_ProducePointReduceValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  type: ProduceEffectType_ProducePointReduceValueDown
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardupgrade
  type: ProduceEffectType_ProduceCardUpgrade
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardduplicate
  type: ProduceEffectType_ProduceCardDuplicate
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardduplicateupgrade
  type: ProduceEffectType_ProduceCardDuplicateUpgrade
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardchange
  type: ProduceEffectType_ProduceCardChange
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardchangeupgrade
  type: ProduceEffectType_ProduceCardChangeUpgrade
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecarddelete
  type: ProduceEffectType_ProduceCardDelete
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  type: ProduceEffectType_ProducePointAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  type: ProduceEffectType_ProducePointGetDisable
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  type: ProduceEffectType_ProduceItemGetDisable
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  type: ProduceEffectType_ProduceDrinkGetDisable
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  type: ProduceEffectType_ProduceReward
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewardcard
  resourceType: ProduceResourceType_ProduceCard
  type: ProduceEffectType_ProduceReward
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  resourceType: ProduceResourceType_ProduceDrink
  type: ProduceEffectType_ProduceReward
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewardpoint
  resourceType: ProduceResourceType_ProducePoint
  type: ProduceEffectType_ProduceReward
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producereward
  type: ProduceEffectType_ProduceRewardSet
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewardcard
  resourceType: ProduceResourceType_ProduceCard
  type: ProduceEffectType_ProduceRewardSet
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewarddrink
  resourceType: ProduceResourceType_ProduceDrink
  type: ProduceEffectType_ProduceRewardSet
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producerewardpoint
  resourceType: ProduceResourceType_ProducePoint
  type: ProduceEffectType_ProduceRewardSet
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-auditionparameterbonusmultiple
  type: ProduceEffectType_AuditionParameterBonusMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-sp
  type: ProduceEffectType_LessonSpChangeRatePermilAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-vocal
  iconAssetId: img_general_icon_produce-effect_pict-sp
  type: ProduceEffectType_LessonVocalSpChangeRatePermilAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-dance
  iconAssetId: img_general_icon_produce-effect_pict-sp
  type: ProduceEffectType_LessonDanceSpChangeRatePermilAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-visual
  iconAssetId: img_general_icon_produce-effect_pict-sp
  type: ProduceEffectType_LessonVisualSpChangeRatePermilAddition
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-sp
  type: ProduceEffectType_LessonSpChangeRatePermilDown
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-examstatusenchant
  type: ProduceEffectType_ExamStatusEnchant
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-lessonpresentproducecardrewardcountup
  type: ProduceEffectType_LessonPresentProduceCardRewardCountUp
- backgroundAssetId: img_general_icon_produce-effect_bg-negative
  iconAssetId: img_general_icon_produce-effect_pict-lessonpresentproducecardrewardcountdown
  type: ProduceEffectType_LessonPresentProduceCardRewardCountDown
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopPriceDiscountMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceCardPriceDiscountMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceCardUpgradePriceSpecify
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-shop
  type: ProduceEffectType_ShopProduceCardDeletePriceSpecify
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-money
  type: ProduceEffectType_ProduceResultRewardMoneyUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardenhancepoint
  type: ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventstaminarecover
  type: ProduceEffectType_SupportCardEventStaminaRecoverUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventpointrecover
  type: ProduceEffectType_SupportCardEventProducePointAdditionValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventparameterrecover
  type: ProduceEffectType_SupportCardEventParameterAdditionValueUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventprobability
  type: ProduceEffectType_SupportCardEventProbabilityUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepointadditionvalue
  type: ProduceEffectType_LessonPresentProducePointUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-supportcardeventprobability
  type: ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producecardselectrerollcount
  type: ProduceEffectType_ProduceCardSelectRerollCountUp
- backgroundAssetId: img_general_icon_produce-effect_bg-positive
  iconAssetId: img_general_icon_produce-effect_pict-producepoint
  type: ProduceEffectType_ProducePointAdditionDisableTrigger