- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeFinalLessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-final-normal-01
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeMid1LessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeMid2LessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeFinalAuditionRefresh
  title: 最終試験前日
  assetId: adv_produce-refresh_001_before-audition-final
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeMid1AuditionRefresh
  title: 中間試験前日
  assetId: adv_produce-refresh_001_before-audition-mid
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_BeforeMid2AuditionRefresh
  title: 中間試験前日
  assetId: adv_produce-refresh_001_before-audition-mid
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_Opening
  title: 定期公演『初』
  assetId: adv_pstory_001_cmmn_world-explanation
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultTrueEnd
  title: 最終評価は……
  assetId: adv_presult_001_final-true
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultA
  title: 最終評価は……
  assetId: adv_presult_001_final-normal-01
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultB
  title: 最終評価は……
  assetId: adv_presult_001_final-normal-02
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultC
  title: 最終評価は……
  assetId: adv_presult_001_final-normal-03
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultFailedFinal
  title: 最終評価は……
  assetId: adv_presult_001_final-failure
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultFailedMid1
  title: 最終評価は……
  assetId: adv_presult_001_mid-failure
- produceType: ProduceType_FirstStar
  type: ProduceAdvType_ProduceResultFailedMid2
  title: 最終評価は……
  assetId: adv_presult_001_mid-failure
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeFinalLessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-final-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid1LessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid2LessonHard
  title: 追い込みレッスン開始！
  assetId: adv_pstory_001_cmmn_before-hard-mid-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeFinalAuditionRefresh
  title: 最終オーディション前日
  assetId: adv_produce-refresh_002_before-audition-final
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid1AuditionRefresh
  title: １次オーディション前日
  assetId: adv_produce-refresh_002_before-audition-mid_01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid2AuditionRefresh
  title: ２次オーディション前日
  assetId: adv_produce-refresh_002_before-audition-mid_02
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeFinalAuditionSelect
  title: 最終オーディション選択
  assetId: adv_pstory_002_cmmn_before-audition-select-final-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid1AuditionSelect
  title: １次オーディション選択
  assetId: adv_pstory_002_cmmn_before-audition-select-a-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_BeforeMid2AuditionSelect
  title: ２次オーディション選択
  assetId: adv_pstory_002_cmmn_before-audition-select-b-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_StepSkip
  title: 今日は休もう
  assetId: adv_produce-week-skip_002_01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Opening
  title: NEXT IDOL AUDITION
  assetId: adv_pstory_002_cmmn_world-explanation
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultTrueEnd
  title: 最終評価は……
  assetId: adv_presult_002_final-true-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultA
  title: 最終評価は……
  assetId: adv_presult_002_final-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultB
  title: 最終評価は……
  assetId: adv_presult_002_final-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultC
  title: 最終評価は……
  assetId: adv_presult_002_final-normal-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultFailedFinal
  title: 最終評価は……
  assetId: adv_presult_002_failure
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultFailedMid1
  title: 最終評価は……
  assetId: adv_presult_002_failure
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_ProduceResultFailedMid2
  title: 最終評価は……
  assetId: adv_presult_002_failure