- produceId: produce-004
  characterId: amao
  forceLiveCommonIdolCardId: i_card-amao-3-007
  unlockConditionSetId: cd-dearness_level-amao-10
- produceId: produce-004
  characterId: fktn
  forceLiveCommonIdolCardId: i_card-fktn-3-007
  unlockConditionSetId: cd-dearness_level-fktn-10
- produceId: produce-004
  characterId: hrnm
  forceLiveCommonIdolCardId: i_card-hrnm-3-007
  unlockConditionSetId: cd-dearness_level-hrnm-10
- produceId: produce-004
  characterId: hski
  forceLiveCommonIdolCardId: i_card-hski-3-008
  unlockConditionSetId: cd-dearness_level-hski-10
- produceId: produce-004
  characterId: hume
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-hume-10
- produceId: produce-004
  characterId: jsna
  forceLiveCommonIdolCardId: i_card-jsna-3-002
  unlockConditionSetId: cd-dearness_level-jsna-10
- produceId: produce-004
  characterId: kcna
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-kcna-10
- produceId: produce-004
  characterId: kllj
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-kllj-10
- produceId: produce-004
  characterId: shro
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-shro-10
- produceId: produce-004
  characterId: ssmk
  forceLiveCommonIdolCardId: ""
  unlockConditionSetId: cd-dearness_level-ssmk-10
- produceId: produce-004
  characterId: ttmr
  forceLiveCommonIdolCardId: i_card-ttmr-3-007
  unlockConditionSetId: cd-dearness_level-ttmr-10