- type: ProduceCardGrowEffectType_LessonAdd
  name: パラメータ値増加
  produceDescriptionId: Label_LessonAdd
  produceCardCustomizeTemplate: パラメータ+
- type: ProduceCardGrowEffectType_LessonReduce
  name: パラメータ値減少
  produceDescriptionId: Label_LessonReduce
  produceCardCustomizeTemplate: パラメータ-
- type: ProduceCardGrowEffectType_LessonCountAdd
  name: パラメータ上昇回数増加
  produceDescriptionId: Label_LessonCountAdd
  produceCardCustomizeTemplate: パラメータ上昇回数+
- type: ProduceCardGrowEffectType_LessonCountReduce
  name: パラメータ上昇回数減少
  produceDescriptionId: Label_LessonCountReduce
  produceCardCustomizeTemplate: パラメータ上昇回数-
- type: ProduceCardGrowEffectType_BlockAdd
  name: 元気値増加
  produceDescriptionId: Label_BlockAdd
  produceCardCustomizeTemplate: 元気+
- type: ProduceCardGrowEffectType_BlockReduce
  name: 元気値減少
  produceDescriptionId: Label_BlockReduce
  produceCardCustomizeTemplate: 元気-
- type: ProduceCardGrowEffectType_FullPowerPointAdd
  name: 全力値値増加
  produceDescriptionId: Label_FullPowerPointAdd
  produceCardCustomizeTemplate: 全力値+
- type: ProduceCardGrowEffectType_FullPowerPointReduce
  name: 全力値値減少
  produceDescriptionId: Label_FullPowerPointReduce
  produceCardCustomizeTemplate: 全力値-
- type: ProduceCardGrowEffectType_CostBuffReduce
  name: 強化状態コスト値減少
  produceDescriptionId: Label_CostBuffReduce
  produceCardCustomizeTemplate: 強化状態コスト値-
- type: ProduceCardGrowEffectType_CostBuffAdd
  name: 強化状態コスト値増加
  produceDescriptionId: Label_CostBuffAdd
  produceCardCustomizeTemplate: 強化状態コスト値+
- type: ProduceCardGrowEffectType_CostReduce
  name: コスト値減少
  produceDescriptionId: Label_CostReduce
  produceCardCustomizeTemplate: コスト値-
- type: ProduceCardGrowEffectType_CostAdd
  name: コスト値増加
  produceDescriptionId: Label_CostAdd
  produceCardCustomizeTemplate: コスト値+
- type: ProduceCardGrowEffectType_CostPenetrateReduce
  name: 体力消費コスト値減少
  produceDescriptionId: Label_CostPenetrateReduce
  produceCardCustomizeTemplate: 体力消費コスト値-
- type: ProduceCardGrowEffectType_CostPenetrateAdd
  name: 体力消費コスト値増加
  produceDescriptionId: Label_CostPenetrateAdd
  produceCardCustomizeTemplate: 体力消費コスト値+
- type: ProduceCardGrowEffectType_ParameterBuffTurnAdd
  name: 好調値増加
  produceDescriptionId: Label_ParameterBuffTurnAdd
  produceCardCustomizeTemplate: 好調+
- type: ProduceCardGrowEffectType_ParameterBuffTurnReduce
  name: 好調値減少
  produceDescriptionId: Label_ParameterBuffTurnReduce
  produceCardCustomizeTemplate: 好調-
- type: ProduceCardGrowEffectType_LessonBuffAdd
  name: 集中値増加
  produceDescriptionId: Label_LessonBuffAdd
  produceCardCustomizeTemplate: 集中+
- type: ProduceCardGrowEffectType_LessonBuffReduce
  name: 集中値減少
  produceDescriptionId: Label_LessonBuffReduce
  produceCardCustomizeTemplate: 集中-
- type: ProduceCardGrowEffectType_ReviewAdd
  name: 好印象値増加
  produceDescriptionId: Label_ReviewAdd
  produceCardCustomizeTemplate: 好印象+
- type: ProduceCardGrowEffectType_ReviewReduce
  name: 好印象値減少
  produceDescriptionId: Label_ReviewReduce
  produceCardCustomizeTemplate: 好印象-
- type: ProduceCardGrowEffectType_AggressiveAdd
  name: やる気値増加
  produceDescriptionId: Label_AggressiveAdd
  produceCardCustomizeTemplate: やる気+
- type: ProduceCardGrowEffectType_AggressiveReduce
  name: やる気値減少
  produceDescriptionId: Label_AggressiveReduce
  produceCardCustomizeTemplate: やる気-
- type: ProduceCardGrowEffectType_CardDrawAdd
  name: ドロー枚数増加
  produceDescriptionId: Label_CardDrawAdd
  produceCardCustomizeTemplate: カードを引く+
- type: ProduceCardGrowEffectType_CardDrawReduce
  name: ドロー枚数減少
  produceDescriptionId: Label_CardDrawReduce
  produceCardCustomizeTemplate: カードを引く-
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnAdd
  name: 絶好調値増加
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnAdd
  produceCardCustomizeTemplate: 絶好調+
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnReduce
  name: 絶好調値減少
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnReduce
  produceCardCustomizeTemplate: 絶好調-
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnAdd
  name: 消費体力減少値増加
  produceDescriptionId: Label_StaminaConsumptionDownTurnAdd
  produceCardCustomizeTemplate: 消費体力減少+
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnReduce
  name: 消費体力減少値減少
  produceDescriptionId: Label_StaminaConsumptionDownTurnReduce
  produceCardCustomizeTemplate: 消費体力減少-
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnAdd
  name: 消費体力増加値減少
  produceDescriptionId: Label_StaminaConsumptionAddTurnAdd
  produceCardCustomizeTemplate: 消費体力増加+
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnReduce
  name: 消費体力増加値増加
  produceDescriptionId: Label_StaminaConsumptionAddTurnReduce
  produceCardCustomizeTemplate: 消費体力増加-
- type: ProduceCardGrowEffectType_EffectAdd
  name: 効果追加
  produceDescriptionId: Label_EffectAdd
  produceCardCustomizeTemplate: 効果追加
- type: ProduceCardGrowEffectType_EffectDelete
  name: 効果削除
  produceDescriptionId: Label_EffectDelete
  produceCardCustomizeTemplate: 効果削除
- type: ProduceCardGrowEffectType_EffectChange
  name: 効果置換
  produceDescriptionId: Label_EffectChange
  produceCardCustomizeTemplate: 効果変更
- type: ProduceCardGrowEffectType_CardStatusEnchantChange
  name: 成長効果置換
  produceDescriptionId: Label_CardStatusEnchantChange
  produceCardCustomizeTemplate: 成長変更
- type: ProduceCardGrowEffectType_PlayTriggerChange
  name: 使用可能条件を置換
  produceDescriptionId: Label_PlayTriggerChange
  produceCardCustomizeTemplate: 条件変更
- type: ProduceCardGrowEffectType_PlayEffectTriggerChange
  name: 効果発動条件を置換
  produceDescriptionId: Label_PlayEffectTriggerChange
  produceCardCustomizeTemplate: 条件変更
- type: ProduceCardGrowEffectType_PlayMovePositionTypeChange
  name: 使用後移動先変更
  produceDescriptionId: Label_PlayMovePositionTypeChange
  produceCardCustomizeTemplate: 移動先変更
- type: ProduceCardGrowEffectType_InitialAdd
  name: 開始時手札効果付与
  produceDescriptionId: Label_InitialAdd
  produceCardCustomizeTemplate: 開始時手札に入る