- type: ProduceCardGrowEffectType_LessonAdd
  name: パラメータ上昇値+
  produceDescriptionId: Label_LessonAdd
- type: ProduceCardGrowEffectType_LessonReduce
  name: パラメータ上昇値-
  produceDescriptionId: Label_LessonReduce
- type: ProduceCardGrowEffectType_LessonCountAdd
  name: パラメータ上昇回数+
  produceDescriptionId: Label_LessonCountAdd
- type: ProduceCardGrowEffectType_LessonCountReduce
  name: パラメータ上昇回数-
  produceDescriptionId: Label_LessonCountReduce
- type: ProduceCardGrowEffectType_BlockAdd
  name: 元気増加値+
  produceDescriptionId: Label_BlockAdd
- type: ProduceCardGrowEffectType_BlockReduce
  name: 元気増加値-
  produceDescriptionId: Label_BlockReduce
- type: ProduceCardGrowEffectType_FullPowerPointAdd
  name: 全力値増加値+
  produceDescriptionId: Label_FullPowerPointAdd
- type: ProduceCardGrowEffectType_FullPowerPointReduce
  name: 全力値増加値-
  produceDescriptionId: Label_FullPowerPointReduce
- type: ProduceCardGrowEffectType_CostBuffReduce
  name: 強化状態コスト減少
  produceDescriptionId: Label_CostBuffReduce
- type: ProduceCardGrowEffectType_CostBuffAdd
  name: 強化状態コスト増加
  produceDescriptionId: Label_CostBuffAdd
- type: ProduceCardGrowEffectType_CostReduce
  name: コスト減少
  produceDescriptionId: Label_CostReduce
- type: ProduceCardGrowEffectType_CostAdd
  name: コスト増加
  produceDescriptionId: Label_CostAdd
- type: ProduceCardGrowEffectType_CostPenetrateReduce
  name: 体力消費コスト減少
  produceDescriptionId: Label_CostPenetrateReduce
- type: ProduceCardGrowEffectType_CostPenetrateAdd
  name: 体力消費コスト増加
  produceDescriptionId: Label_CostPenetrateAdd
- type: ProduceCardGrowEffectType_ParameterBuffTurnAdd
  name: 好調増加値+
  produceDescriptionId: Label_ParameterBuffTurnAdd
- type: ProduceCardGrowEffectType_ParameterBuffTurnReduce
  name: 好調増加値-
  produceDescriptionId: Label_ParameterBuffTurnReduce
- type: ProduceCardGrowEffectType_LessonBuffAdd
  name: 集中増加値+
  produceDescriptionId: Label_LessonBuffAdd
- type: ProduceCardGrowEffectType_LessonBuffReduce
  name: 集中増加値-
  produceDescriptionId: Label_LessonBuffReduce
- type: ProduceCardGrowEffectType_ReviewAdd
  name: 好印象増加値+
  produceDescriptionId: Label_ReviewAdd
- type: ProduceCardGrowEffectType_ReviewReduce
  name: 好印象増加値-
  produceDescriptionId: Label_ReviewReduce
- type: ProduceCardGrowEffectType_AggressiveAdd
  name: やる気増加値+
  produceDescriptionId: Label_AggressiveAdd
- type: ProduceCardGrowEffectType_AggressiveReduce
  name: やる気増加値-
  produceDescriptionId: Label_AggressiveReduce
- type: ProduceCardGrowEffectType_CardDrawAdd
  name: ドロー枚数+
  produceDescriptionId: Label_CardDrawAdd
- type: ProduceCardGrowEffectType_CardDrawReduce
  name: ドロー枚数-
  produceDescriptionId: Label_CardDrawReduce
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnAdd
  name: 絶好調増加値+
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnAdd
- type: ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnReduce
  name: 絶好調増加値-
  produceDescriptionId: Label_ParameterBuffMultiplePerTurnReduce
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnAdd
  name: 消費体力-増加値+
  produceDescriptionId: Label_StaminaConsumptionDownTurnAdd
- type: ProduceCardGrowEffectType_StaminaConsumptionDownTurnReduce
  name: 消費体力-増加値-
  produceDescriptionId: Label_StaminaConsumptionDownTurnReduce
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnAdd
  name: 消費体力+増加値-
  produceDescriptionId: Label_StaminaConsumptionAddTurnAdd
- type: ProduceCardGrowEffectType_StaminaConsumptionAddTurnReduce
  name: 消費体力+増加値+
  produceDescriptionId: Label_StaminaConsumptionAddTurnReduce
- type: ProduceCardGrowEffectType_EffectAdd
  name: 効果追加
  produceDescriptionId: Label_EffectAdd
- type: ProduceCardGrowEffectType_EffectDelete
  name: 効果削除
  produceDescriptionId: Label_EffectDelete
- type: ProduceCardGrowEffectType_EffectChange
  name: 効果置換
  produceDescriptionId: Label_EffectChange
- type: ProduceCardGrowEffectType_CardStatusEnchantChange
  name: 成長効果置換
  produceDescriptionId: Label_CardStatusEnchantChange
- type: ProduceCardGrowEffectType_PlayTriggerChange
  name: 使用可能条件を置換
  produceDescriptionId: Label_PlayTriggerChange
- type: ProduceCardGrowEffectType_PlayEffectTriggerChange
  name: 効果発動条件を置換
  produceDescriptionId: Label_PlayEffectTriggerChange
- type: ProduceCardGrowEffectType_PlayMovePositionTypeChange
  name: 使用後移動先変更
  produceDescriptionId: Label_PlayMovePositionTypeChange
- type: ProduceCardGrowEffectType_InitialAdd
  name: 開始時手札効果付与
  produceDescriptionId: Label_InitialAdd