- type: ProduceStepType_EventSchool
  name: 学園活動
  produceDescriptionLabelId: Label_ProduceStepType_EventSchool
- type: ProduceStepType_Present
  name: プレゼント
  produceDescriptionLabelId: Label_ProduceStepType_Present