- name: ボーカル上昇
  type: ProduceEffectType_VocalAddition
- name: ダンス上昇
  type: ProduceEffectType_DanceAddition
- name: ビジュアル上昇
  type: ProduceEffectType_VisualAddition
- name: ボーカル低下
  type: ProduceEffectType_VocalDown
- name: ダンス低下
  type: ProduceEffectType_DanceDown
- name: ビジュアル低下
  type: ProduceEffectType_VisualDown
- name: ボーカルレッスンボーナス+
  type: ProduceEffectType_VocalGrowthRateAddition
- name: ダンスレッスンボーナス+
  type: ProduceEffectType_DanceGrowthRateAddition
- name: ビジュアルレッスンボーナス+
  type: ProduceEffectType_VisualGrowthRateAddition
- name: ボーカルレッスンボーナス-
  type: ProduceEffectType_VocalGrowthRateDown
- name: ダンスレッスンボーナス-
  type: ProduceEffectType_DanceGrowthRateDown
- name: ビジュアルレッスンボーナス-
  type: ProduceEffectType_VisualGrowthRateDown
- name: 体力回復
  type: ProduceEffectType_StaminaRecoverFix
- name: 体力割合回復
  type: ProduceEffectType_StaminaRecoverMultiple
- name: 体力減少
  type: ProduceEffectType_StaminaReduceFix
- name: 体力割合減少
  type: ProduceEffectType_StaminaReduceMultiple
- name: 体力変更
  type: ProduceEffectType_StaminaSpecify
- name: 体力回復量増加
  type: ProduceEffectType_StaminaRecoverValueUp
- name: 体力回復量減少
  type: ProduceEffectType_StaminaRecoverValueDown
- name: 体力減少量増加
  type: ProduceEffectType_StaminaReduceValueUp
- name: 体力減少量軽減
  type: ProduceEffectType_StaminaReduceValueDown
- name: 体力回復無効
  type: ProduceEffectType_StaminaRecoverDisable
- name: 最大体力増加
  type: ProduceEffectType_MaxStaminaAddition
- name: 最大体力減少
  type: ProduceEffectType_MaxStaminaReduceFix
- name: 最大体力割合減少
  type: ProduceEffectType_MaxStaminaReduceMultiple
- name: Pポイント減少
  type: ProduceEffectType_ProducePointReduceFix
- name: Pポイント割合減少
  type: ProduceEffectType_ProducePointReduceMultiple
- name: Pポイント変更
  type: ProduceEffectType_ProducePointSpecify
- name: Pポイント獲得量増加
  type: ProduceEffectType_ProducePointAdditionValueUp
- name: Pポイント獲得量減少
  type: ProduceEffectType_ProducePointAdditionValueDown
- name: Pポイント減少量増加
  type: ProduceEffectType_ProducePointReduceValueUp
- name: Pポイント減少量減少
  type: ProduceEffectType_ProducePointReduceValueDown
- name: 強化
  produceDescriptionId: Label_ProduceCardUpgrade
  type: ProduceEffectType_ProduceCardUpgrade
- name: コピー
  produceDescriptionId: Label_ProduceCardDuplicate
  type: ProduceEffectType_ProduceCardDuplicate
- name: コピーして強化
  type: ProduceEffectType_ProduceCardDuplicateUpgrade
- name: チェンジ
  produceDescriptionId: Label_ProduceCardChange
  type: ProduceEffectType_ProduceCardChange
- name: チェンジして強化
  type: ProduceEffectType_ProduceCardChangeUpgrade
- name: 削除
  produceDescriptionId: Label_ProduceCardDelete
  type: ProduceEffectType_ProduceCardDelete
- name: Pポイント獲得
  type: ProduceEffectType_ProducePointAddition
- name: Pポイント獲得不可
  type: ProduceEffectType_ProducePointGetDisable
- name: Pアイテム獲得不可
  type: ProduceEffectType_ProduceItemGetDisable
- name: Pドリンク獲得不可
  type: ProduceEffectType_ProduceDrinkGetDisable
- name: 報酬獲得
  type: ProduceEffectType_ProduceReward
- name: 報酬獲得
  type: ProduceEffectType_ProduceRewardSet
- name: スコアボーナス増加
  type: ProduceEffectType_AuditionParameterBonusMultiple
- name: SPレッスン発生率増加
  type: ProduceEffectType_LessonSpChangeRatePermilAddition
- name: ボーカルSPレッスン発生率増加
  type: ProduceEffectType_LessonVocalSpChangeRatePermilAddition
- name: ダンスSPレッスン発生率増加
  type: ProduceEffectType_LessonDanceSpChangeRatePermilAddition
- name: ビジュアルSPレッスン発生率増加
  type: ProduceEffectType_LessonVisualSpChangeRatePermilAddition
- name: SPレッスン発生率減少
  type: ProduceEffectType_LessonSpChangeRatePermilDown
- name: レッスン時発生効果
  type: ProduceEffectType_ExamStatusEnchant
- name: レッスン報酬のスキルカード選択肢追加
  type: ProduceEffectType_LessonPresentProduceCardRewardCountUp
- name: レッスン報酬のスキルカード選択肢減少
  type: ProduceEffectType_LessonPresentProduceCardRewardCountDown
- name: 相談割引
  type: ProduceEffectType_ShopPriceDiscountMultiple
- name: 相談のスキルカードを割引
  produceDescriptionId: Label_ShopProduceCardPriceDiscountMultiple
  type: ProduceEffectType_ShopProduceCardPriceDiscountMultiple
- name: 相談のPドリンクを割引
  type: ProduceEffectType_ShopProduceDrinkPriceDiscountMultiple
- name: 相談のスキルカード強化を割引
  type: ProduceEffectType_ShopProduceCardUpgradePriceDiscountMultiple
- name: 相談のスキルカード強化を変更
  type: ProduceEffectType_ShopProduceCardUpgradePriceSpecify
- name: 相談のスキルカード削除を割引
  type: ProduceEffectType_ShopProduceCardDeletePriceDiscountMultiple
- name: 相談のスキルカード強化を変更
  type: ProduceEffectType_ShopProduceCardDeletePriceSpecify
- name: プロデュース完了時の獲得マニー増加
  type: ProduceEffectType_ProduceResultRewardMoneyUp
- name: プロデュース完了時のサポートPt増加
  type: ProduceEffectType_ProduceResultRewardSupportCardEnhancePointUp
- name: サポートイベントの体力回復量増加
  type: ProduceEffectType_SupportCardEventStaminaRecoverUp
- name: サポートイベントのPポイント獲得量増加
  type: ProduceEffectType_SupportCardEventProducePointAdditionValueUp
- name: サポートイベントのパラメータ上昇量増加
  type: ProduceEffectType_SupportCardEventParameterAdditionValueUp
- name: サポートイベント発生率増加
  type: ProduceEffectType_SupportCardEventProbabilityUp
- name: レッスン報酬のPポイント獲得量増加
  type: ProduceEffectType_LessonPresentProducePointUp
- name: レッスンサポート発生率増加
  type: ProduceEffectType_SupportCardProduceCardUpgradeProbabilityUp
- name: 再抽選回数増加
  type: ProduceEffectType_ProduceCardSelectRerollCountUp
- name: 初期Pポイント増加
  type: ProduceEffectType_ProducePointAdditionDisableTrigger