- characterId: amao
  motionAssetId: mot_all_chr_amao_glad-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-amao-1-000_produce_start-01
- characterId: amao
  motionAssetId: mot_all_chr_amao_yes-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-amao-1-000_produce_start-01
- characterId: amao
  motionAssetId: mot_all_chr_amao_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: fktn
  motionAssetId: mot_all_chr_fktn_kime-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-fktn-1-000_produce_start-01
- characterId: fktn
  motionAssetId: mot_all_chr_fktn_yaruki-002_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-fktn-1-000_produce_start-01
- characterId: fktn
  motionAssetId: mot_all_chr_fktn_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: hrnm
  motionAssetId: mot_all_chr_hrnm_glad-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-hrnm-1-000_produce_start-01
- characterId: hrnm
  motionAssetId: mot_all_chr_hrnm_glad-002_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-hrnm-1-000_produce_start-01
- characterId: hrnm
  motionAssetId: mot_all_chr_hrnm_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: hski
  motionAssetId: mot_all_chr_hski_doya-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-hski-1-000_produce_start-01
- characterId: hski
  motionAssetId: mot_all_chr_hski_doya-002_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-hski-1-000_produce_start-01
- characterId: hski
  motionAssetId: mot_all_chr_hski_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: kcna
  motionAssetId: mot_all_chr_kcna_yaruki-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-kcna-1-000_produce_start-01
- characterId: kcna
  motionAssetId: mot_all_chr_cmmn_ojigi-b-002_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-kcna-1-000_produce_start-01
- characterId: kcna
  motionAssetId: mot_all_chr_kcna_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: kllj
  motionAssetId: mot_all_chr_cmmn_yes-d-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-kllj-1-000_produce_start-01
- characterId: kllj
  motionAssetId: mot_all_chr_kllj_yes-003_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-kllj-1-000_produce_start-01
- characterId: kllj
  motionAssetId: mot_all_chr_kllj_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: shro
  motionAssetId: mot_all_chr_shro_glad-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-shro-1-000_produce_start-01
- characterId: shro
  motionAssetId: mot_all_chr_shro_yes-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-shro-1-000_produce_start-01
- characterId: shro
  motionAssetId: mot_all_chr_shro_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: ssmk
  motionAssetId: mot_all_chr_ssmk_tanoshimu-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-ssmk-1-000_produce_start-01
- characterId: ssmk
  motionAssetId: mot_all_chr_ssmk_kime-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-ssmk-1-000_produce_start-01
- characterId: ssmk
  motionAssetId: mot_all_chr_ssmk_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1
- characterId: ttmr
  facialAssetId: mot_all_chr_cmmn_facial-all-normal1-egao1_in
  motionAssetId: mot_all_chr_cmmn_talk-013_in
  motionType: ProduceStartMotionType_Reaction
  number: 1
  voiceAssetId: sud_vo_system_cidol-ttmr-1-000_produce_start-01
- characterId: ttmr
  motionAssetId: mot_all_chr_cmmn_yes-c-001_in
  motionType: ProduceStartMotionType_Reaction
  number: 2
  voiceAssetId: sud_vo_system_cidol-ttmr-1-000_produce_start-01
- characterId: ttmr
  motionAssetId: mot_all_chr_ttmr_idle-001_pose
  motionType: ProduceStartMotionType_Wait
  number: 1