- continueCount: 3
  examStartAlertStaminaThreshold: 10
  id: p_setting-1
  produceAuditionTrendAssessmentPermil: 200
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700
- continueCount: 3
  examStartAlertStaminaThreshold: 10
  id: p_setting-2
  produceAuditionTrendAssessmentPermil: 200
  produceDrinkPossessLimit: 3
  refreshStaminaRecoveryPermil: 700