- locationType: ProduceScheduleLocationType_ProducerRoom1
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c00
  monitorMovieId: ""
  produceGroupIds: []
- locationType: ProduceScheduleLocationType_ProducerRoom2
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c01
  monitorMovieId: ""
  produceGroupIds: []
- locationType: ProduceScheduleLocationType_Classroom
  backgroundAssetId: env_3d_prod_schoolroom-01-00-noon
  sceneLayoutId: schoolroom-01-00-noon-c00
  monitorMovieId: ""
  produceGroupIds: []
- locationType: ProduceScheduleLocationType_Rooftop
  backgroundAssetId: env_3d_prod_rooftop-01-00-noon
  sceneLayoutId: rooftop-01-00-noon-c00
  monitorMovieId: ""
  produceGroupIds: []
- locationType: ProduceScheduleLocationType_Courtyard
  backgroundAssetId: env_3d_prod_courtyard-01-00-noon
  sceneLayoutId: courtyard-01-00-noon-c00
  monitorMovieId: ""
  produceGroupIds: []
- locationType: ProduceScheduleLocationType_ProducerRoom3
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c02
  monitorMovieId: mov_general_monitor_03
  produceGroupIds:
  - produce_group-002
- locationType: ProduceScheduleLocationType_ProducerRoom4
  backgroundAssetId: env_3d_prod_classroom-00-00-noon
  sceneLayoutId: classroom-00-00-noon-c03
  monitorMovieId: ""
  produceGroupIds:
  - produce_group-002
- locationType: ProduceScheduleLocationType_Classroom2
  backgroundAssetId: env_3d_prod_schoolroom-01-01-noon
  sceneLayoutId: schoolroom-01-01-noon-c01
  monitorMovieId: ""
  produceGroupIds:
  - produce_group-002
- locationType: ProduceScheduleLocationType_Rooftop2
  backgroundAssetId: env_3d_prod_rooftop-01-01-noon
  sceneLayoutId: rooftop-01-01-noon-c01
  monitorMovieId: ""
  produceGroupIds:
  - produce_group-002
- locationType: ProduceScheduleLocationType_Courtyard2
  backgroundAssetId: env_3d_prod_schoolgarden-01-00-noon
  sceneLayoutId: schoolgarden-01-00-noon-c00
  monitorMovieId: ""
  produceGroupIds:
  - produce_group-002