- id: self_lesson-produce_004-01-normal
  progressLevel: 1
  stamina: 6
  parameter: 80
- id: self_lesson-produce_004-01-sp
  progressLevel: 1
  stamina: 8
  parameter: 100
- id: self_lesson-produce_004-02-normal
  progressLevel: 1
  stamina: 6
  parameter: 100
- id: self_lesson-produce_004-02-sp
  progressLevel: 1
  stamina: 8
  parameter: 120
- id: self_lesson-produce_004-03-normal
  progressLevel: 1
  stamina: 6
  parameter: 120
- id: self_lesson-produce_004-03-sp
  progressLevel: 1
  stamina: 8
  parameter: 150