- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: amao
  title: 10.5話
  assetId: adv_dear_amao_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: fktn
  title: 10.5話
  assetId: adv_dear_fktn_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: hrnm
  title: 10.5話
  assetId: adv_dear_hrnm_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: hski
  title: 10.5話
  assetId: adv_dear_hski_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: hume
  title: 10.5話
  assetId: adv_dear_hume_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: kcna
  title: 10.5話
  assetId: adv_dear_kcna_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: kllj
  title: 10.5話
  assetId: adv_dear_kllj_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: shro
  title: 10.5話
  assetId: adv_dear_shro_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: ssmk
  title: 10.5話
  assetId: adv_dear_ssmk_010-01
- produceType: ProduceType_NextIdolAudition
  type: ProduceAdvType_Introduction
  characterId: ttmr
  title: 10.5話
  assetId: adv_dear_ttmr_010-01