- level: 1
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
- level: 2
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 40
  unlockTargets:
    - id: p_card-01-act-1_001
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-1_006
      type: ProducerLevelUnlockType_ProduceCard
- level: 3
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 160
  unlockTargets:
    - id: p_card-00-act-2_009
      type: ProducerLevelUnlockType_ProduceCard
- level: 4
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 430
  unlockTargets:
    - id: p_card-01-men-1_025
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-1_032
      type: ProducerLevelUnlockType_ProduceCard
- level: 5
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 880
  unlockTargets:
    - type: ProducerLevelUnlockType_ShopProduceCardUpgrade
    - id: p_card-00-men-3_012
      type: ProducerLevelUnlockType_ProduceCard
- level: 6
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 1530
  unlockTargets:
    - id: p_card-01-act-2_033
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-2_045
      type: ProducerLevelUnlockType_ProduceCard
- level: 7
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 2380
  unlockTargets:
    - id: p_card-01-act-2_042
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_050
      type: ProducerLevelUnlockType_ProduceCard
- level: 8
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 3430
  unlockTargets:
    - id: pdrink_00-2-001
      type: ProducerLevelUnlockType_ProduceDrink
- level: 9
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 4680
  unlockTargets:
    - id: p_card-01-act-1_023
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-1_033
      type: ProducerLevelUnlockType_ProduceCard
- level: 10
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 6130
  unlockTargets:
    - quantity: 1
      type: ProducerLevelUnlockType_ProduceCardSelectRerollCount
    - id: p_card-00-men-3_011
      type: ProducerLevelUnlockType_ProduceCard
- level: 11
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 7780
  unlockTargets:
    - id: p_card-01-act-3_030
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-3_001
      type: ProducerLevelUnlockType_ProduceCard
- level: 12
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 9630
  unlockTargets:
    - id: p_card-01-act-3_031
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-3_038
      type: ProducerLevelUnlockType_ProduceCard
- level: 13
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 11730
  unlockTargets:
    - id: p_card-01-act-1_020
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-1_003
      type: ProducerLevelUnlockType_ProduceCard
- level: 14
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 14080
  unlockTargets:
    - id: p_card-01-act-1_021
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-1_004
      type: ProducerLevelUnlockType_ProduceCard
- level: 15
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 16730
  unlockTargets:
    - type: ProducerLevelUnlockType_ShopProduceCardDelete
    - id: pdrink_00-3-005
      type: ProducerLevelUnlockType_ProduceDrink
    - id: pdrink_00-2-003
      type: ProducerLevelUnlockType_ProduceDrink
- level: 16
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 19680
  unlockTargets:
    - id: p_card-00-men-1_007
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-00-men-1_005
      type: ProducerLevelUnlockType_ProduceCard
- level: 17
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 22930
  unlockTargets:
    - id: p_card-01-men-2_034
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_058
      type: ProducerLevelUnlockType_ProduceCard
- level: 18
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 26480
  unlockTargets:
    - id: p_card-01-men-2_038
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_004
      type: ProducerLevelUnlockType_ProduceCard
- level: 19
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 30330
  unlockTargets:
    - id: p_card-01-men-1_008
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-1_009
      type: ProducerLevelUnlockType_ProduceCard
- level: 20
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 34530
  unlockTargets:
    - id: p_card-01-men-2_035
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_054
      type: ProducerLevelUnlockType_ProduceCard
- level: 21
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 39130
  unlockTargets:
    - id: pdrink_01-2-005
      type: ProducerLevelUnlockType_ProduceDrink
    - id: pdrink_02-2-006
      type: ProducerLevelUnlockType_ProduceDrink
- level: 22
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 44130
  unlockTargets:
    - id: p_card-01-act-2_002
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_052
      type: ProducerLevelUnlockType_ProduceCard
- level: 23
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 49530
  unlockTargets:
    - id: p_card-00-men-2_012
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-00-men-2_014
      type: ProducerLevelUnlockType_ProduceCard
- level: 24
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 55330
  unlockTargets:
    - id: p_card-01-act-2_032
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-act-2_048
      type: ProducerLevelUnlockType_ProduceCard
- level: 25
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 61630
  unlockTargets:
    - id: p_card-01-men-3_006
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-3_002
      type: ProducerLevelUnlockType_ProduceCard
- level: 26
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 68430
  unlockTargets:
    - id: pdrink_01-3-004
      type: ProducerLevelUnlockType_ProduceDrink
    - id: pdrink_02-3-007
      type: ProducerLevelUnlockType_ProduceDrink
- level: 27
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 75730
  unlockTargets:
    - id: pdrink_01-3-002
      type: ProducerLevelUnlockType_ProduceDrink
    - id: pdrink_02-3-006
      type: ProducerLevelUnlockType_ProduceDrink
- level: 28
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 83630
  unlockTargets:
    - id: p_card-01-men-2_036
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_008
      type: ProducerLevelUnlockType_ProduceCard
- level: 29
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 92130
  unlockTargets:
    - id: p_card-01-men-2_040
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-2_051
      type: ProducerLevelUnlockType_ProduceCard
- level: 30
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 101430
  unlockTargets:
    - id: p_card-01-men-3_036
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-3_004
      type: ProducerLevelUnlockType_ProduceCard
- level: 31
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 111530
  unlockTargets:
    - id: p_card-01-men-2_037
      type: ProducerLevelUnlockType_ProduceCard
- level: 32
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 122430
  unlockTargets:
    - id: p_card-02-men-2_057
      type: ProducerLevelUnlockType_ProduceCard
- level: 33
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 134130
  unlockTargets:
    - id: p_card-01-act-2_001
      type: ProducerLevelUnlockType_ProduceCard
- level: 34
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 146630
  unlockTargets:
    - id: p_card-02-act-2_049
      type: ProducerLevelUnlockType_ProduceCard
- level: 35
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 160130
  unlockTargets:
    - id: p_card-00-men-3_003
      type: ProducerLevelUnlockType_ProduceCard
- level: 36
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 174630
  unlockTargets:
    - id: p_card-01-men-2_041
      type: ProducerLevelUnlockType_ProduceCard
- level: 37
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 190130
  unlockTargets:
    - id: p_card-02-men-3_041
      type: ProducerLevelUnlockType_ProduceCard
- level: 38
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 206630
  unlockTargets:
    - id: p_card-01-men-3_033
      type: ProducerLevelUnlockType_ProduceCard
- level: 39
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 224130
  unlockTargets:
    - id: p_card-02-men-3_044
      type: ProducerLevelUnlockType_ProduceCard
- level: 40
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 243130
  unlockTargets:
    - id: p_card-00-men-3_005
      type: ProducerLevelUnlockType_ProduceCard
- level: 41
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 263130
  unlockTargets:
    - id: p_card-01-act-3_029
      type: ProducerLevelUnlockType_ProduceCard
- level: 42
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 284130
  unlockTargets:
    - id: p_card-02-men-3_043
      type: ProducerLevelUnlockType_ProduceCard
- level: 43
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 306130
  unlockTargets:
    - id: p_card-01-act-3_010
      type: ProducerLevelUnlockType_ProduceCard
- level: 44
  reward:
    quantity: 1
    resourceId: item-staminaregen-1
    resourceType: ResourceType_Item
  totalExp: 329130
  unlockTargets:
    - id: p_card-02-act-3_039
      type: ProducerLevelUnlockType_ProduceCard
- level: 45
  reward:
    quantity: 50
    resourceType: ResourceType_JewelTotal
  totalExp: 354130
  unlockTargets:
    - id: p_card-01-men-3_035
      type: ProducerLevelUnlockType_ProduceCard
    - id: p_card-02-men-3_042
      type: ProducerLevelUnlockType_ProduceCard