- id: card_enchant-e_trigger-exam_card_play_after-p_card_search-active_skill-playing-0_1-g_effect-lesson_add-5
  produceExamTriggerId: e_trigger-exam_card_play_after-p_card_search-active_skill-playing-0_1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-5
  triggerCount: 0
- id: card_enchant-e_trigger-exam_card_play_after-p_card_search-mental_skill-playing-0_1-g_effect-block_add-5
  produceExamTriggerId: e_trigger-exam_card_play_after-p_card_search-mental_skill-playing-0_1
  produceCardGrowEffectIds:
  - g_effect-block_add-5
  triggerCount: 0
- id: card_enchant-e_trigger-exam_card_play_after-p_card_search-playing-effect_group-visible-exam_concentration-000-0_1-2-g_effect-lesson_add-10-g_effect-cost_add-1
  produceExamTriggerId: e_trigger-exam_card_play_after-p_card_search-playing-effect_group-visible-exam_concentration-000-0_1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-10
  - g_effect-cost_add-1
  triggerCount: 2
- id: card_enchant-e_trigger-exam_card_play_after-p_card_search-playing-effect_group-visible-exam_concentration-000-0_1-2-g_effect-lesson_add-15-g_effect-cost_add-1
  produceExamTriggerId: e_trigger-exam_card_play_after-p_card_search-playing-effect_group-visible-exam_concentration-000-0_1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-15
  - g_effect-cost_add-1
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-1-g_effect-lesson_add-10
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-10
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_concentration-1-g_effect-lesson_add-8
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-8
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_concentration-1-g_effect-lesson_count_add-1
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_count_add-1
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-cost_reduce-1-g_effect-lesson_add-16
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-cost_reduce-1
  - g_effect-lesson_add-16
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-cost_reduce-1-g_effect-lesson_add-21
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-cost_reduce-1
  - g_effect-lesson_add-21
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-10
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-10
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-15
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-15
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-15-g_effect-cost_add-1
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-15
  - g_effect-cost_add-1
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-20
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-20
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-25-g_effect-cost_add-1
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-25
  - g_effect-cost_add-1
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_concentration-2-g_effect-lesson_add-6
  produceExamTriggerId: e_trigger-exam_stance_change_concentration
  produceCardGrowEffectIds:
  - g_effect-lesson_add-6
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-2-g_effect-lesson_add-4
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-4
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-2-g_effect-lesson_add-6
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-6
  triggerCount: 2
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-4-g_effect-lesson_add-15
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-15
  triggerCount: 4
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-4-g_effect-lesson_add-20
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-20
  triggerCount: 4
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-g_effect-lesson_add-2
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-2
  triggerCount: 0
- id: card_enchant-e_trigger-exam_stance_change_count_interval-1-g_effect-lesson_add-4
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-1
  produceCardGrowEffectIds:
  - g_effect-lesson_add-4
  triggerCount: 0
- id: card_enchant-e_trigger-exam_stance_change_count_interval-2-3-g_effect-lesson_add-4
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-2
  produceCardGrowEffectIds:
  - g_effect-lesson_add-4
  triggerCount: 3
- id: card_enchant-e_trigger-exam_stance_change_count_interval-2-3-g_effect-lesson_add-7
  produceExamTriggerId: e_trigger-exam_stance_change_count_interval-2
  produceCardGrowEffectIds:
  - g_effect-lesson_add-7
  triggerCount: 3
- id: card_enchant-e_trigger-exam_stance_change_full_power-1-g_effect-full_power_point_add-1-g_effect-cost_add-1
  produceExamTriggerId: e_trigger-exam_stance_change_full_power
  produceCardGrowEffectIds:
  - g_effect-full_power_point_add-1
  - g_effect-cost_add-1
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_full_power-1-g_effect-lesson_add-20
  produceExamTriggerId: e_trigger-exam_stance_change_full_power
  produceCardGrowEffectIds:
  - g_effect-lesson_add-20
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_full_power-1-g_effect-lesson_add-30
  produceExamTriggerId: e_trigger-exam_stance_change_full_power
  produceCardGrowEffectIds:
  - g_effect-lesson_add-30
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_preservation-1-g_effect-block_add-10
  produceExamTriggerId: e_trigger-exam_stance_change_preservation
  produceCardGrowEffectIds:
  - g_effect-block_add-10
  triggerCount: 1
- id: card_enchant-e_trigger-exam_stance_change_preservation-1-g_effect-block_add-5
  produceExamTriggerId: e_trigger-exam_stance_change_preservation
  produceCardGrowEffectIds:
  - g_effect-block_add-5
  triggerCount: 1
- id: card_enchant-e_trigger-exam_status_change-exam_full_power_point-3-g_effect-lesson_add-11
  produceExamTriggerId: e_trigger-exam_status_change-exam_full_power_point
  produceCardGrowEffectIds:
  - g_effect-lesson_add-11
  triggerCount: 3
- id: card_enchant-e_trigger-exam_status_change-exam_full_power_point-3-g_effect-lesson_add-6
  produceExamTriggerId: e_trigger-exam_status_change-exam_full_power_point
  produceCardGrowEffectIds:
  - g_effect-lesson_add-6
  triggerCount: 3