- type: ProducePlanType_Common
  name: 共通
  produceDescriptionLabelId: Label_ProducePlanType0
  planDetailProduceDescriptionLabelId: Label_ProducePlanType0
- type: ProducePlanType_Plan1
  name: 【センス専用】
  produceDescriptionLabelId: Label_ProduceSkillPlanType1
  planDetailProduceDescriptionLabelId: Label_ProducePlanType1
- type: ProducePlanType_Plan2
  name: 【ロジック専用】
  produceDescriptionLabelId: Label_ProduceSkillPlanType2
  planDetailProduceDescriptionLabelId: Label_ProducePlanType2
- type: ProducePlanType_Plan3
  name: 【アノマリー専用】
  produceDescriptionLabelId: Label_ProduceSkillPlanType3
  planDetailProduceDescriptionLabelId: Label_ProducePlanType3